
services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/practice

  frontend:
    build: ./front-end/bloging
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

volumes:
  mongo-data:
